FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_BASE=http://localhost:4000
COPY package*.json ./
RUN npm install
COPY . .
ENV VITE_API_BASE=${VITE_API_BASE}
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
