\set ON_ERROR_STOP on

drop table if exists asset_rent_line_item cascade;
drop table if exists assets_rent cascade;
drop table if exists court_reservation_line_item cascade;
drop table if exists court_reservation cascade;
drop table if exists sale_line_item cascade;
drop table if exists sale cascade;
drop table if exists work_order_line_item cascade;
drop table if exists work_order cascade;
drop table if exists coaching_line_item cascade;
drop table if exists coaching_header cascade;
drop table if exists service_type cascade;
drop table if exists technician cascade;
drop table if exists product cascade;
drop table if exists asset cascade;
drop table if exists coach cascade;
drop table if exists court cascade;
drop table if exists member cascade;

create table member (
  id bigint primary key generated by default as identity,
  name text not null,
  phone text,
  mail text,
  detail text,
  gender text,
  tier_id bigint default 1,
  current_reward_point bigint default 0,
  "lifetime point" bigint default 0
);

create table court (
  court_number bigint primary key generated by default as identity,
  court_code text unique not null,
  price numeric(12,2) default 0,
  price_weekend numeric(12,2) default 0
);

create table coach (
  coach_id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  name text not null,
  phone_no text,
  speciality text,
  hourly_rate numeric(12,2) default 0
);

create table asset (
  id bigint primary key generated by default as identity,
  code text unique not null,
  type text,
  brand text,
  purchase_date date,
  price numeric(12,2) default 0
);

create table product (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  category text,
  unit_id bigint,
  unit_price numeric(12,2) default 0,
  stock bigint default 0
);

create table technician (
  id bigint primary key generated by default as identity,
  code text unique,
  name text not null,
  phone text
);

create table service_type (
  id bigint primary key generated by default as identity,
  name text not null
);

create table court_reservation (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  reservation_code text unique not null,
  reservation_date date,
  member_id bigint references member(id),
  total_hour numeric(12,2) default 0,
  amount_sum numeric(12,2) default 0,
  discount numeric(12,2) default 0,
  net_amount numeric(12,2) default 0,
  points_earned numeric(12,2) default 0
);

create table court_reservation_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  court_reservation_id bigint references court_reservation(id) on delete cascade,
  court_number bigint,
  date date,
  start_time time,
  end_time time,
  total_time numeric(12,2) default 0,
  extended_price numeric(12,2) default 0
);

create table assets_rent (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  rent_code text unique not null,
  member_id bigint references member(id),
  hours numeric(12,2) default 0,
  date date,
  total_price numeric(12,2) default 0,
  discounted_price numeric(12,2) default 0,
  deposit numeric(12,2) default 0,
  due numeric(12,2) default 0
);

create table asset_rent_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  rent_id bigint references assets_rent(id) on delete cascade,
  date date,
  asset_id bigint references asset(id),
  unit_price numeric(12,2) default 0,
  amount bigint default 1,
  condition_out text,
  condition_in text,
  returned bigint default 0,
  damage_fee numeric(12,2) default 0,
  extended_price numeric(12,2) default 0
);

create table coaching_header (
  session_no bigint primary key generated by default as identity,
  created_at timestamp default now(),
  coaching_code text not null,
  date date,
  member_id bigint references member(id),
  coach_id bigint references coach(coach_id),
  total_coaching_fee numeric(12,2) default 0,
  member_discount_amount numeric(12,2) default 0,
  net_coaching_fee numeric(12,2) default 0,
  points_earned numeric(12,2) default 0
);

create table coaching_line_item (
  line_id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  session_no bigint references coaching_header(session_no) on delete cascade,
  training_date date,
  start_time time,
  end_time time,
  skill_focus text,
  hours numeric(12,2) default 0,
  hourly_rate numeric(12,2) default 0,
  extended_fee numeric(12,2) default 0
);

create table work_order (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  member_id bigint references member(id),
  technician_id bigint references technician(id),
  date date,
  expected_finish_date date,
  status text default 'Pending',
  total_material_cost numeric(12,2) default 0,
  total_labor_cost numeric(12,2) default 0,
  member_discount numeric(12,2) default 0,
  grand_total numeric(12,2) default 0,
  total numeric(12,2) default 0,
  points_earned numeric(12,2) default 0
);

create table work_order_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  work_order_id bigint references work_order(id) on delete cascade,
  racket_model_product_id bigint references product(id),
  product_id bigint references product(id),
  service_id bigint references service_type(id),
  tension_required numeric(12,2),
  material_cost numeric(12,2) default 0,
  labor_fee numeric(12,2) default 0,
  line_total numeric(12,2) default 0
);

create table sale (
  id bigint primary key generated by default as identity,
  receipt_code text unique not null,
  sale_date date,
  member_id bigint references member(id),
  purchase_method text default 'cash',
  total_price numeric(12,2) default 0,
  discount numeric(12,2) default 0,
  net_total numeric(12,2) default 0,
  points_earned numeric(12,2) default 0,
  points_redeemed numeric(12,2) default 0
);

create table sale_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  sale_id bigint references sale(id) on delete cascade,
  product_id bigint references product(id),
  unit_price numeric(12,2) default 0,
  quantity bigint default 1,
  extended_price numeric(12,2) default 0
);
