create table if not exists tiers (
    id bigint primary key generated by default as identity,
    created_at timestamp default now(),
    name varchar unique not null,
    min_point bigint not null,
    discount_percentage decimal(10,2) null,
    point_multiplier decimal(10,2) not null
);

create table if not exists users (
    id bigint primary key generated by default as identity,
    created_at timestamp default now(),
    name varchar not null,
    phone varchar unique not null,
    mail varchar unique not null,
    detail text null,
    gender varchar not null,
    tier_id  bigint references tiers(id) on delete restrict on update cascade,
    current_reward_point bigint not null,
    lifetime_point bigint not null
);

create table if not exists assets (
    id bigint primary key generated by default as identity,
    created_at timestamp default now(),
    code varchar unique not null,
    type varchar not null,
    brand varchar not null,
    purchase_date date not null,
    price decimal(10,2) not null
);

create table if not exists asset_rents (
    id bigint primary key generated by default as identity,
    rent_code varchar unique not null,
    created_at timestamp default now(),
    member_id  bigint references users(id) on delete restrict on update cascade,
    hours bigint not null,
    date date not null,
    amount_sum decimal(10,2) not null,
    discount decimal(10,2) not null,
    deposit decimal(10,2) not null,
    due decimal(10,2) not null
);

create table if not exists asset_rent_items (
    id bigint primary key generated by default as identity,
    created_at timestamp default now(),
    rent_id  bigint references asset_rents(id) on delete restrict on update cascade,
    date date not null,
    asset_id  bigint references assets(id) on delete restrict on update cascade,
    unit_price decimal(10,2) not null,
    amount bigint not null,
    condition_out varchar not null,
    returned bigint not null,
    condition_in varchar not null,
    damage_fee decimal(10,2) not null,
    extended_price decimal(10,2) not null
);


alter table users add constraint chk_points check (current_reward_point >= 0 and lifetime_point >= 0);
alter table users add constraint chk_gender check (gender in ('male','female','other'));
alter table asset_rents add constraint chk_asset_rents_money check (amount_sum >= 0 and deposit >= 0 and price >= 0);
alter table asset_rent_items add constraint chk_asset_rent_items_money check (unit_price >= 0 and damage_fee >= 0 and extended_price >= 0);
alter table asset_rent_items add constraint unique_asset_per_rent unique (rent_id, asset_id);
alter table asset_rent_items add constraint chk_returned (returned = 0 or returned = 1);

create index if not exists idx_asset_rents_member on asset_rents(member_id);
create index if not exists idx_asset_rent_items_rent on asset_rent_items(rent_id);
create index if not exists idx_asset_rent_items_asset on asset_rent_items(asset_id);